---
- hosts: all
  vars:
    hostname: "{{ ansible_hostname }}"
    doc_root: "/srv/share"

    front_controller: index.html
  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
  tasks:
    - block:
      - name: install packages
        apt:
          name: "{{ item }}"
          state: latest
          update_cache: yes
        with_items:
          - acl
          - curl
          - nginx
          - git
          - nodejs
          - npm
        notify:
          - restart nginx

      - name: link nodejs to node
        file:
          src: /usr/bin/nodejs
          dest: /usr/bin/node
          state: link

      - name: install npm packages
        npm:
          name: gulp-cli
          global: true

      - name:
        file:
          path: /var/ssl
          state: directory

      - name: create self-signed SSL cert
        command: openssl req -new -nodes -x509 -subj "/C=US/ST=Oregon/L=Portland/O=IT/CN=${ansible_fqdn}" -days 3650 -keyout /var/ssl/server.key -out /var/ssl/server.crt -extensions v3_ca creates=/var/ssl/server.crt
        notify: restart nginx

      - name: install vhost template
        template:
          src: "nginx_vhost_simple.j2"
          dest: /etc/nginx/sites-available/default
        notify:
          - restart nginx

      - name: start and enable nginx
        service:
          name: nginx
          state: started
          enabled: true
  become: true
